import { useMemo, useState, type ReactNode } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import type { AddEnvironmentInput, SavedEnvironmentRecord } from "../types";
import { colors, spacing } from "../theme";

export function HomeScreen(props: {
  readonly environments: ReadonlyArray<SavedEnvironmentRecord>;
  readonly error: string | null;
  readonly onReload: () => Promise<void>;
  readonly onAddEnvironment: (input: AddEnvironmentInput) => Promise<SavedEnvironmentRecord>;
  readonly onRemoveEnvironment: (environmentId: string) => Promise<void>;
  readonly onSelectEnvironment: (environmentId: string) => void;
}) {
  const [label, setLabel] = useState("");
  const [pairingUrl, setPairingUrl] = useState("");
  const [host, setHost] = useState("");
  const [pairingCode, setPairingCode] = useState("");
  const [mode, setMode] = useState<"pairing-url" | "host-and-code">("pairing-url");
  const [submitting, setSubmitting] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);

  const helperText = useMemo(
    () =>
      mode === "pairing-url"
        ? "Paste the full pairing URL generated by T3 Code."
        : "Enter the reachable host and the one-time pairing code.",
    [mode],
  );

  const handleSubmit = async () => {
    setSubmitting(true);
    setFormError(null);
    try {
      await props.onAddEnvironment(
        mode === "pairing-url"
          ? { label, pairingUrl }
          : {
              label,
              host,
              pairingCode,
            },
      );
      setLabel("");
      setPairingUrl("");
      setHost("");
      setPairingCode("");
    } catch (error) {
      setFormError(error instanceof Error ? error.message : "Failed to add environment.");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
      <Text style={styles.title}>T3 Code Mobile</Text>
      <Text style={styles.subtitle}>
        Pair this device with a desktop or headless T3 Code server and control it natively.
      </Text>

      <View style={styles.card}>
        <View style={styles.segmentedRow}>
          <SegmentButton
            active={mode === "pairing-url"}
            label="Pairing URL"
            onPress={() => setMode("pairing-url")}
          />
          <SegmentButton
            active={mode === "host-and-code"}
            label="Host + code"
            onPress={() => setMode("host-and-code")}
          />
        </View>

        <Text style={styles.helper}>{helperText}</Text>

        <Field label="Label">
          <TextInput
            placeholder="Studio MacBook"
            placeholderTextColor={colors.textMuted}
            style={styles.input}
            value={label}
            onChangeText={setLabel}
          />
        </Field>

        {mode === "pairing-url" ? (
          <Field label="Pairing URL">
            <TextInput
              placeholder="https://tailnet.example/pair#token=..."
              placeholderTextColor={colors.textMuted}
              style={[styles.input, styles.multilineInput]}
              multiline
              autoCapitalize="none"
              autoCorrect={false}
              value={pairingUrl}
              onChangeText={setPairingUrl}
            />
          </Field>
        ) : (
          <>
            <Field label="Host">
              <TextInput
                placeholder="https://100.110.0.12:3773"
                placeholderTextColor={colors.textMuted}
                style={styles.input}
                autoCapitalize="none"
                autoCorrect={false}
                value={host}
                onChangeText={setHost}
              />
            </Field>
            <Field label="Pairing code">
              <TextInput
                placeholder="paste code"
                placeholderTextColor={colors.textMuted}
                style={styles.input}
                autoCapitalize="none"
                autoCorrect={false}
                value={pairingCode}
                onChangeText={setPairingCode}
              />
            </Field>
          </>
        )}

        {(formError ?? props.error) ? (
          <Text style={styles.error}>{formError ?? props.error}</Text>
        ) : null}

        <PrimaryButton label={submitting ? "Pairing…" : "Add environment"} onPress={handleSubmit} />
      </View>

      <View style={styles.headerRow}>
        <Text style={styles.sectionTitle}>Saved environments</Text>
        <Pressable onPress={() => void props.onReload()}>
          <Text style={styles.actionText}>Refresh</Text>
        </Pressable>
      </View>

      {props.environments.length === 0 ? (
        <View style={styles.emptyState}>
          <Text style={styles.emptyStateTitle}>No paired environments yet</Text>
          <Text style={styles.emptyStateBody}>
            Add one above using the pairing link or the host and pairing code.
          </Text>
        </View>
      ) : (
        props.environments.map((environment) => (
          <View key={environment.environmentId} style={styles.environmentCard}>
            <Pressable
              onPress={() => props.onSelectEnvironment(environment.environmentId)}
              style={styles.environmentCardBody}
            >
              <Text style={styles.environmentTitle}>{environment.label}</Text>
              <Text style={styles.environmentMeta}>{environment.httpBaseUrl}</Text>
              <Text style={styles.environmentMeta}>
                Last connected {environment.lastConnectedAt ?? "never"}
              </Text>
            </Pressable>
            <Pressable onPress={() => void props.onRemoveEnvironment(environment.environmentId)}>
              <Text style={[styles.actionText, styles.dangerText]}>Remove</Text>
            </Pressable>
          </View>
        ))
      )}
    </ScrollView>
  );
}

function Field(props: { readonly label: string; readonly children: ReactNode }) {
  return (
    <View style={styles.field}>
      <Text style={styles.fieldLabel}>{props.label}</Text>
      {props.children}
    </View>
  );
}

function SegmentButton(props: {
  readonly active: boolean;
  readonly label: string;
  readonly onPress: () => void;
}) {
  return (
    <Pressable
      onPress={props.onPress}
      style={[styles.segmentButton, props.active ? styles.segmentButtonActive : null]}
    >
      <Text
        style={[styles.segmentButtonText, props.active ? styles.segmentButtonTextActive : null]}
      >
        {props.label}
      </Text>
    </Pressable>
  );
}

function PrimaryButton(props: { readonly label: string; readonly onPress: () => void }) {
  return (
    <Pressable onPress={props.onPress} style={styles.primaryButton}>
      <Text style={styles.primaryButtonLabel}>{props.label}</Text>
    </Pressable>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    padding: spacing.lg,
    gap: spacing.lg,
  },
  title: {
    color: colors.text,
    fontSize: 30,
    fontWeight: "700",
  },
  subtitle: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 20,
    padding: spacing.md,
    gap: spacing.md,
  },
  segmentedRow: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  segmentButton: {
    flex: 1,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 12,
    backgroundColor: colors.input,
  },
  segmentButtonActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  segmentButtonText: {
    color: colors.textMuted,
    textAlign: "center",
    fontWeight: "600",
  },
  segmentButtonTextActive: {
    color: colors.text,
  },
  helper: {
    color: colors.textMuted,
    lineHeight: 20,
  },
  field: {
    gap: spacing.xs,
  },
  fieldLabel: {
    color: colors.text,
    fontWeight: "600",
  },
  input: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.input,
    color: colors.text,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  multilineInput: {
    minHeight: 96,
    textAlignVertical: "top",
  },
  error: {
    color: colors.danger,
  },
  primaryButton: {
    backgroundColor: colors.accent,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  primaryButtonLabel: {
    color: colors.text,
    fontWeight: "700",
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "700",
  },
  actionText: {
    color: colors.accent,
    fontWeight: "600",
  },
  dangerText: {
    color: colors.danger,
  },
  emptyState: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  emptyStateTitle: {
    color: colors.text,
    fontWeight: "700",
    fontSize: 16,
  },
  emptyStateBody: {
    color: colors.textMuted,
    lineHeight: 20,
  },
  environmentCard: {
    backgroundColor: colors.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.md,
  },
  environmentCardBody: {
    gap: spacing.xs,
  },
  environmentTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "700",
  },
  environmentMeta: {
    color: colors.textMuted,
    lineHeight: 20,
  },
});
